### ISSUE TITLE
[Question] Access to big onedrive library ask to reconnect

### ISSUE THREAD

**Issue by nowheremanmail** [windows-toolkit/Graph-Controls#34] opened 2020-02-23 21:53 UTC
## Describe the bug
I want to extract all music from a onedrive (25000 files). I'm going thought all folders to get all files and after process several folders, it stops working and ask to reconnect.

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce
Code to extract files ..

```
private async void getAllSongs()
        {
            var provider = ProviderManager.Instance.GlobalProvider;

            if (provider != null && provider.State == ProviderState.SignedIn )
            {
                var musicFolder = await provider.Graph.Me.Drive.Root.ItemWithPath("music").Request().GetAsync();

                var pending = new Queue<Microsoft.Graph.DriveItem>();
                pending.Enqueue(musicFolder);

                while (pending.Count > 0)
                {
                    var item = pending.Dequeue();
                    var children = await provider.Graph.Me.Drive.Items[item.Id].Children.Request().GetAsync();
                    foreach (var i in children)
                    {
                        if (i.Folder != null)
                        {
                            pending.Enqueue(i);
                            System.Diagnostics.Debug.WriteLine("folder " + i.Name);
                        }
                        else
                        {
                            if (i.Audio != null)
                            {
                                //if (validMusicFileTypes.Contains(i.File.ToString))
                                {
                                }
                            }
                        }
                    }
                }
               
            }

```

## Expected behavior
It should be able to process all files without ask to reconnect

## Environment
NuGet Package(s): 
6.1.0-preview1

Package Version(s): 

Windows 10 Build Number:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [x] Insider Build (build number:  19041.84)

App min and target version:
- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [x] October 2018 Update (17763)
- [x] May 2019 Update (18362)
- [ ] Insider Build (xxxxx)

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio 
- [ ] 2017 (version: )
- [x] 2019 (version: ) 
- [ ] 2019 Preview (version: )

```

## Additional context
Add any other context about the problem here.

**Comment by nowheremanmail** [comment] 2020-03-24 07:52
It seems that token it's not reused between different request ...

**Comment by Kyaa-dost** [comment] 2020-03-26 19:12
@kbrons or @cbarkerms any insight on this?

**Comment by michael-hawker** [comment] 2020-03-26 23:03
Thanks for the report @nowheremanmail! I actually think this sounds just like the issue @miracletower was having [over here](https://github.com/MicrosoftDocs/WindowsCommunityToolkitDocs/issues/299).

The token management should be handled by the underlying graph APIs we're using, but that's something we'd need to validate to see if we could remove the Toolkit code from the equation to this problem.

This is the effective code-path we run:
```csharp
            var client = PublicClientApplicationBuilder.Create(clientid)
                .WithAuthority(AzureCloudInstance.AzurePublic, AadAuthorityAudience.AzureAdAndPersonalMicrosoftAccount)
                .WithRedirectUri(redirectUri)
                .WithClientName(ProviderManager.ClientName)
                .WithClientVersion(Assembly.GetExecutingAssembly().GetName().Version.ToString())
                .Build();

            if (scopes == null)
            {
                scopes = new string[] { string.Empty };
            }

            var provider = new InteractiveAuthenticationProvider(client, scopes);

            var account = (await client.GetAccountsAsync()).FirstOrDefault();

            if (account == null)
            {
                // No accounts
                State = ProviderState.SignedOut;
            }
            else
            {
                try
                {
                    // Try and sign-in // TODO: can we use empty scopes?
                    var result = await client.AcquireTokenSilent(new string[] { string.Empty }, account).ExecuteAsync();

                    if (!string.IsNullOrWhiteSpace(result.AccessToken))
                    {
                        State = ProviderState.SignedIn;
                    }
                    else
                    {
                        State = ProviderState.SignedOut;
                    }
                }
                catch (MsalUiRequiredException)
                {
                    await LoginAsync();
                }
                catch (Exception)
                {
                    State = ProviderState.SignedOut;
                }
            }
```

I'm wondering if we could get more details about what might be happening from [these lines](https://github.com/windows-toolkit/Graph-Controls/blob/master/Microsoft.Toolkit.Graph/Providers/MsalProvider.cs#L150-L153). Or if it's going through some other code-path.

As it's either going to be we have setup some of the configuration within our helper incorrectly OR it's a problem within the Graph SDK that we should report.  We could also try updating the dependency of the Graph SDK that we're using to see if it resolves the issue.

@azchohfi since we've been talking about Unit Tests in the main repo, we should figure out a good strategy around that for the Graph components as well too, eh?

**Comment by nowheremanmail** [comment] 2020-03-27 06:43
I didn't test in this version, but in the code you are asking always for a token to seed if it's logged or not (line AcquireTokenSilent), if it's user is logged is getting a new token when really it's not necessary, and after a few request more graph server returns an error.

I revert my code to previous version and it has the similar problem, what I didn't is keep previous token and reused, and only when token is expired I ask for a new one

**Comment by michael-hawker** [comment] 2020-03-27 16:26
@nowheremanmail calling `AcquireTokenSilent` is part of the MSAL guidance as found [here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token). Between this call and the [Graph Auth Library](https://github.com/microsoftgraph/msgraph-sdk-dotnet-auth) we use, we should be following their exact same recommended pattern.

@darrelmiller is there a good way we could understand what this underlying token problem is? It'd be great to be able to better debug what's triggering the token refresh so we can determine the problem area here and if this is an underlying SDK issue or an issue with our implementation of the recommended patterns (or a bug in the documentation describing them)? Thanks!

**Comment by michael-hawker** [comment] 2020-03-27 16:29
We should also try updating our Graph & Graph Auth NuGet packages and checking if the problem goes away, as they have shipped newer versions.

**Comment by nowheremanmail** [comment] 2020-03-28 11:56
I changed library to add some traces and get extra information. At this moment previous code after 16 request is asking for login again, always!

detailed error return by graph is;


```
(True) MSAL 4.7.1.0 MSAL.UAP N/A [03/28/2020 11:53:44 - 60ba4643-84ed-4d87-befe-727cf6108ac6] (wct/6.1.0.0: 6.1.0.0) MSAL.UAP.4.7.1.0.MsalUiRequiredException: 
	ErrorCode: invalid_grant
Microsoft.Identity.Client.MsalUiRequiredException: AADSTS50196: The server terminated an operation because it encountered a client request loop. Please contact your app vendor.
Trace ID: 46be47d7-f5a4-4715-857b-b30811fa0500
Correlation ID: 60ba4643-84ed-4d87-befe-727cf6108ac6
Timestamp: 2020-03-28 11:53:41Z
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext, Boolean addCorrelationId)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendHttpMessageAsync(OAuth2Client client, String tokenEndpoint)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.SilentRequest.RefreshAccessTokenAsync(MsalRefreshTokenCacheItem msalRefreshTokenItem, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.SilentRequest.RefreshRtOrFailAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
	StatusCode: 400 
	ResponseBody: {"error":"invalid_grant","error_description":"AADSTS50196: The server terminated an operation because it encountered a client request loop. Please contact your app vendor.\r\nTrace ID: 46be47d7-f5a4-4715-857b-b30811fa0500\r\nCorrelation ID: 60ba4643-84ed-4d87-befe-727cf6108ac6\r\nTimestamp: 2020-03-28 11:53:41Z","error_codes":[50196],"timestamp":"2020-03-28 11:53:41Z","trace_id":"46be47d7-f5a4-4715-857b-b30811fa0500","correlation_id":"60ba4643-84ed-4d87-befe-727cf6108ac6","error_uri":"https://login.microsoftonline.com/error?code=50196"} 
	Headers: client-request-id: 60ba4643-84ed-4d87-befe-727cf6108ac6
Strict-Transport-Security: max-age=31536000; includeSubDomains
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
Cache-Control: no-store, no-cache
Set-Cookie: fpc=AhTZXuPLA0dAjOtH37-gpCeHpICYFAAAAKcxEdYOAAAA; expires=Mon, 27-Apr-2020 11:53:41 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly; SameSite=None
Date: Sat, 28 Mar 2020 11:53:41 GMT
x-ms-ests-server: 2.1.10244.29 - AMS1 ProdSlices
x-ms-request-id: 46be47d7-f5a4-4715-857b-b30811fa0500
X-Content-Type-Options: nosniff
Pragma: no-cache
x-ms-clitelem: 1,50196,0,,


```

**Comment by nowheremanmail** [comment] 2020-03-28 12:03
Some extra log

```
>>> CreateAsync
>>> TrySilentSignInAsync
>>> AcquireTokenSilent
>>> TOKEN EwCAA8l6...
>>> AuthenticateRequestAsync
>>> AuthenticateRequestAsync
>>> AuthenticateRequestAsync
>>> AuthenticateRequestAsync
>>> AuthenticateRequestAsync
>>> 0 https://graph.microsoft.com:443/beta/me/drive/root:/music:
>>> AuthenticateRequestAsync
>>> 2 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 3 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 4 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 5 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 6 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 7 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 8 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 9 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 10 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CE.../children
>>> AuthenticateRequestAsync
>>> 11 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CE.../children
>>> AuthenticateRequestAsync
>>> 12 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CE.../children
>>> AuthenticateRequestAsync
>>> 13 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4C.../children
>>> AuthenticateRequestAsync
>>> 14 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4C.../children
>>> AuthenticateRequestAsync
>>> 15 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CE.../children
>>> AuthenticateRequestAsync
>>> 16 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4CEA.../children
>>> AuthenticateRequestAsync
>>> 17 https://graph.microsoft.com:443/beta/me/drive/items/147A2A50B4C.../children
>>> AuthenticateRequestAsync
```

**Comment by nowheremanmail** [comment] 2020-03-29 10:07
Checking in more detail logs files, I saw something regarding tokens, always:  "No tokens found for matching authority" 

```
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Looking up access token in the cache.
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Filtering by tenant id item count before 1 after 1
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Filtering by home account id item count before 1 after 1
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Matching entry count -1
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Matching entry count after filtering by scopes - 0
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) No tokens found for matching authority, client_id, user and scopes.
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Refresh token found in the cache? - True
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Resolving authority endpoints... Already resolved? - TRUE
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Checking client info returned from the server..
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Saving Token Response to cache..
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Looking for scopes for the authority in the cache which intersect with Directory.Read.All Files.Read.All
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Intersecting scope entries count - 1
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Matching entries after filtering by user - 1
> >>>>>> (False) MSAL 4.7.1.0 MSAL.UAP N/A [03/29/2020 10:03:43 - eef3630f-8ef7-4cf8-a9a3-86d688cf0aa7] (wct/6.1.0.0: 6.1.0.0) Saving RT in cache...
```

**Comment by nowheremanmail** [comment] 2020-03-29 13:52
Well after more investigation I found the problem but I don't understand why.
on QuickCreate class remove scope from 

` var provider = new InteractiveAuthenticationProvider(client); //, scopes);
`
Changing this line, now grap library is able to find previous token and reused

**Comment by michael-hawker** [comment] 2020-03-30 18:00
@nowheremanmail THANK YOU SO MUCH!!! 🦙❤

This is an amazing investigation and super helpful. I also don't understand what's going on here, but will reach out to the Graph team and get some more details, I'm surprised that passing in scopes has this effect, it may be an oversight.

FYI @darrelmiller

**Comment by darrelmiller** [comment] 2020-03-30 18:11
@nowheremanmail   The issue seems to be happening in the MSAL.NET library.  Could you try updating that lib to the latest version to see if it fixes the issue?  https://www.nuget.org/packages/Microsoft.Identity.Client/4.10.0

If so we can update the dependency in our package.

**Comment by michael-hawker** [comment] 2020-04-14 07:57
@nowheremanmail did you have a chance to test if updating the underlying MSAL dependency made any difference?

**Comment by nowheremanmail** [comment] 2020-04-14 12:47
I've updated to version 4.11.0 but problem is still there

**Comment by michael-hawker** [comment] 2020-04-15 23:43
FYI @darrelmiller - I think we should file an issue on the MSAL.NET repo to point to here then?

**Comment by shweaver-MSFT** [comment] 2021-06-21 19:33
I'm not able to reproduce this on `main` currently. This could be because the MsalProvider has been refactored a bit and no longer attempts to request tokens with an empty scopes array. The Msal library has also been updated to 2.18.4. Although, I admit I don't have the same repro environment with as many files in OneDrive for query.

Closing this for now, and if it becomes an issue again in the future we can reopen.

**Closed** 2021-06-21 19:34 UTC
Labels: Area: Graph, bug :bug:
